apiVersion: v2
name: user-service
description: A Helm chart for User Service
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 16.4.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

